#ifndef _CURRENT_DRIVING_H_
#define _CURRENT_DRIVING_H_
#include <asm/ioctl.h>

typedef enum
{
    AOCFG1PADCTRL = 0,
    AOCFG2PADCTRL,
    ATCFG1PADCTRL,
    ATCFG2PADCTRL,
    CDEV1CFGPADCTRL,
    CDEV2CFGPADCTRL,
    CSUSCFGPADCTRL,
    DAP1CFGPADCTRL,
    DAP2CFGPADCTRL,
    DAP3CFGPADCTRL,
    DAP4CFGPADCTRL,
    DBGCFGPADCTRL,
    LCDCFG1PADCTRL,
    LCDCFG2PADCTRL,
    SDIO2CFGPADCTRL,
    SDIO3CFGPADCTRL,
    SPICFGPADCTRL,
    UAACFGPADCTRL,
    UABCFGPADCTRL,
    UART2CFGPADCTRL,
    UART3CFGPADCTRL,
    VICFG1PADCTRL,
    VICFG2PADCTRL,
    XM2CFGAPADCTRL,
    XM2CFGCPADCTRL,
    XM2CFGDPADCTRL,
    XM2CLKCFGPADCTRL,
    XM2COMPPADCTRL,
    
    SDIO1CFGPADCTRL,
    
    
    CRTCFGPADCTRL,
    DDCCFGPADCTRL,
    GMACFGPADCTRL,
    GMBCFGPADCTRL,
    GMCCFGPADCTRL,
    GMDCFGPADCTRL,
    GMECFGPADCTRL,
    OWRCFGPADCTRL,
    UADCFGPADCTRL,
} PadCtrl;

typedef enum
{
    OHM_400 = 0,
    OHM_200 = 1,
    OHM_100 = 2,
    OHM_50 = 3,
} OHM;


struct current_driving_ctrl_t {
	PadCtrl padctrl;
	OHM ohm;
};


#define CURRENT_DRIVING_IOC_MAGIC 	'z'
#define CURRENT_DRIVING_IOC_WRITE					_IOW(CURRENT_DRIVING_IOC_MAGIC, 0, struct current_driving_ctrl_t)
#endif